### ISSUE TITLE
Machine image gets immediately deleted after creation

### ISSUE THREAD

**Issue by marc-** [chef/chef-provisioning-docker#37]
Running recipe from example:
```ruby
machine_image 'web_server' do
  recipe 'apache'
  machine_options :docker_options => {
      :base_image => {
          :name => 'ubuntu',
          :repository => 'ubuntu',
          :tag => '14.04'
      }
  }
end
```
After chef-client exited, no docker images are accessible.
This happens due to [following change](https://github.com/chef/chef-provisioning/blame/master/lib/chef/provider/machine_image.rb#L84) in latest version if chef-provisioning (v1.0.1) .

**Comment by randomcamel** [comment]
Should be fixed by PR #47.
