### ISSUE TITLE
Chef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 12829

### ISSUE THREAD

**Issue by kri5** [chef/chef-provisioning-docker#38]
The below error appears when using the chef-provisioning-docker driver for providing a machine that need to sync cookbook with chef-zero (chef-client -z ...)

    Chef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 12829

There already is an issue opened in chef-zero, (chef/chef-zero#126) but it might be related to chef-provisioning-docker, as with the same cookbooks and recipes, it works for other drivers (ie. vagrant)

**Comment by kri5** [comment]
chef/chef-zero:#126

**Comment by kri5** [comment]
chef/chef-zero#126

**Comment by marc-** [comment]
I guess it may come from [chef-provisioning-docker:chef_zero_http_proxy](https://github.com/chef/chef-provisioning-docker/blob/master/lib/chef/provisioning/docker_driver/chef_zero_http_proxy.rb#L57).
Though, it mostly work for chef 11.18 for me.

**Comment by cbuben** [comment]
See notes in https://github.com/chef/chef-provisioning-docker/issues/39

**Comment by jkeiser** [comment]
Yep, this is fixed with #39!  Thanks :)

**Comment by chriscameron** [comment]
I've hit this with all providers that I've tried with, Fog / Digital Ocean, AWS and SSH as providers.
