### ISSUE TITLE
Connection to Docker image fails

### ISSUE THREAD

**Issue by swatiswjain** [chef/chef-provisioning-docker#44]
Trying to run the command 
CHEF_DRIVER=docker chef-client -z <chefprov_env>.rb 
with the sample recipe at https://github.com/chef/chef-provisioning-docker

The image is created and I can see it listed but the the attempt to create the container fails with the following exception:
 ===============================================================================
    Error executing action `converge` on resource 'machine[machine1]'
===============================================================================    
    Docker::Error::NotFoundError
    ----------------------------
    No such container: machine1

If I manually run the command sudo docker run -t -i <image_created>a container instance is created. I tried running the chef-client in sudo mode but it is not able to access the chef-provisioning-docker gem in sudo mode

**Comment by marc-** [comment]
Try `chef-provisioning` v0.19 instead of latest.

**Comment by swatiswjain** [comment]
It doesn't help either. 
Given below are the versions I have for the relevant gems. I am using docker:
$ gem list | grep chef-provisioning
chef-provisioning (0.19, 0.18)
chef-provisioning-aws (0.2.1)
chef-provisioning-azure (0.1)
chef-provisioning-docker (0.5.2)
chef-provisioning-fog (0.12)
chef-provisioning-vagrant (0.8.1)

Also, how does it try to connect to the docker. Is it a correct assumption that it will sudo to create the docker container.

**Comment by swatiswjain** [comment]
Got the issue resolved. It was due to proxy settings for docker.
