### ISSUE TITLE
gemspec relies on very old chef-provisioning version

### ISSUE THREAD

**Issue by rmoriz** [chef/chef-provisioning-docker#45]
see https://github.com/chef/chef-provisioning-docker/blob/master/chef-provisioning-docker.gemspec#L16

```
Updating git://github.com/chef/chef-provisioning-google.git
Updating git://github.com/chef/chef-provisioning-docker.git
Updating git://github.com/chef/chef-provisioning-ssh.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "chef-provisioning":
  In Gemfile:
    chef-provisioning-docker (>= 0) ruby depends on
      chef-provisioning (~> 0.9) ruby

    chef-provisioning (>= 0) ruby
```

**Comment by tyler-ball** [comment]
@randomcamel This is fixed in master, correct?

**Comment by fnichol** [comment]
We should be good here in master as of 03a1b6daf4f84d28a7e3b9045a320b44113c16c9 which updates to `~> 1.0`.

**Later...**

Hey, and @randomcamel just cut a [0.7.0](https://github.com/chef/chef-provisioning-docker/releases/tag/v0.7) release!

---

@rmoriz, if I got this wrong, could you reopen? Thank you! :cake: :tophat:
