### ISSUE TITLE
Will the re-write have the ability to do docker commands from the provisioning run?

### ISSUE THREAD

**Issue by rberger** [chef/chef-provisioning-docker#5]
Will the re-write keep the ability to do all the docker commands in the chef-metal recipes? 

I.E. the feature where the provisioning recipe can do all the things that can be done in a docker file, but it doesn't require a chef-client in the docker container. It does it via the docker api from the provisioning chef-client run to the docker container via the docker api.

This is a super power and makes chef-metal-docker a much better docker provisioner than dockerfiles.

When should we start playing with this new version?

**Comment by jkeiser** [comment]
Calling it good :)
