### ISSUE TITLE
chef-provisioning-docker doesn't implement :destroy for machine_image

### ISSUE THREAD

**Issue by randomcamel** [chef/chef-provisioning-docker#50]
I'm not sure how it fits into idiomatic Docker workflows, but since it's doable with the CLI `docker` tool, it seems like an obvious thing for us to have.

**Comment by marc-** [comment]
It seems it just needs to be added. See https://github.com/chef/chef-provisioning-docker/blob/master/lib/chef/provisioning/docker_driver/driver.rb#L164

**Comment by randomcamel** [comment]
Yep. I may put it into 0.7 with your fixes for chef-provisioning 1.x.

**Comment by marc-** [comment]
This feature seems is not blocked by chef-provisioning 1.x compatibility issue. So, I'm not sure if you need to include my changes, since I didn't get any feedback from @jkeiser or @tyler-ball  regarding to my PR so far. So we don't know when it will (if it will ever) get into master.

**Comment by tyler-ball** [comment]
@marc- we appreciate all the work you got together in https://github.com/chef/chef-provisioning-docker/pull/47 - we're going to get it merged.  We have a couple of people new to Docker so we're all trying to get up to speed on that PR.  Sorry we have been unresponsive for a while!

**Comment by randomcamel** [comment]
Looks like #16 implements this and needs a little bit of tweaking to get it over the line. (I have another branch that will add specs for it.)
