### ISSUE TITLE
Update /etc/hosts of Docker container

### ISSUE THREAD

**Issue by Priminus** [chef/chef-provisioning-docker#82]
Anyway to do this yet, since Docker supports the add-hosts option?
Couldn't see anything in the docker-api yet but could be wrong.
Tried this in machine, not working:
:command => 'echo "172.17.0.1  myserver" >> /etc/hosts'

**Comment by jkeiser** [comment]
@Priminus can you try the `jk/more-options` branch from https://github.com/chef/chef-provisioning-docker/pull/83? It should support `docker_options: { add_hosts: "myserver=127.17.0.1" }`, or alternatively `docker_options: { container_config: { "HostConfig" => { "ExtraHosts" => "myserver=127.17.0.1" } } }`

I haven't had time to test every parameter added in that PR yet, but hopefully this will work for you.

**Comment by Priminus** [comment]
Tried it, couple of issues so far:
- Port doesn't parse like it did previously, for example I have this in machine_options:
:ports => [443]
It works without your PR, but with PR I get:
```ruby
MethodError: undefined method `split' for 443:Fixnum
/root/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-docker-0.8.0/lib/chef/provisioning/docker_driver/docker_run_options.rb:540:in `parse_port'
```
Trouble is the docker cookbook where you lifted this from is accepting a String (e.g. port '80:80'), whereas it's documented in CPD as a number. Revert to previous, or change to new format?
```ruby
      if docker_options[:ports]
        docker_options[:ports].each do |portnum|
          args << '-p'
          args << "#{portnum}"
        end
```

- Line 497 of docker_run_options:
config["HostConfig"]["Ulimits"] << { "Name": type, "Soft": soft, "Hard": hard }
It's expecting { "Name" => type, "Soft" => soft, "Hard" => hard }

**Comment by jkeiser** [comment]
@Priminus thanks so much for looking! I'll see if I can repro the `add_hosts` issue.

**Comment by jkeiser** [comment]
@priminus one thing: it's `:add_host`, not `:add_hosts`. There's been enough confusion (even though I've been replicating the command line option names) that I'll add plurals of all array things :)

**Comment by Priminus** [comment]
@jkeiser tried add_host as well and that didn't work. Neither does the container_config.
The hosts file on the container populates really differently than before.
Prior:
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      662a3ca975c0

After:
127.0.0.1   chefserver.vagrant.local chefserver local
host localhost.localdomain localhost4 localhost4.loca
ldomain4
::1         localhost localhost.localdomain localhost
6 localhost6.localdomain6

The latter seems to be a duplicate of the container host, which is wrong behaviour. This might be the reason.

**Comment by jkeiser** [comment]
@Priminus I discovered a bug with add_hosts: when we create the converge container (where we run chef-client), we set `NetworkMode: host`. That conflicts with `add_hosts`. I've pushed a fix to the branch (and added `:add_hosts` and fixed the `ports` issue) if you want to give it a whirl.

**Comment by Priminus** [comment]
@jkeiser thanks I'll try that now!

**Comment by jkeiser** [comment]
Note I'm still having issues with it (even though it got farther). The issues are so weird that I'm wondering if it's my machine, though.

**Comment by Priminus** [comment]
@jkeiser for a start, NetworkMode defaults to 'bridge', which was what I've been using. Having it set to host messes things up, because now the network isn't containerized.

**Comment by jkeiser** [comment]
@priminus that will only happen while you are doing `chef-client`, though. The final container--the command you finally run--will (should?) start up in the default NetworkMode.

**Comment by jkeiser** [comment]
If it doesn't, that is bug.

I checked in a fix to the branch to make pull work and make stop/delete a bit more reliable.

**Comment by jkeiser** [comment]
@priminus when I run this recipe:

```
machine 'supertest' do
  machine_options(
    docker_options: {
      base_image: {
        name: 'ubuntu',
        repository: 'ubuntu',
        tag: 'latest',
      },
      command: "sh -c 'sleep 10000'"
    },
    convergence_options: { ssl_verify_mode: 'verify_none' }
  )
end
```

and `docker inspect supertest` when it is done, it has `"NetworkMode": "default"` (which is also what happens if I use `docker create`). If you're looking at `chef-converge.supertest`, you are looking at the container where we run `chef-client` (which is a different, intermediate step).

**Comment by Priminus** [comment]
@jkeiser Hmmm...yes I'm looking at the chef-converge one.
I was originally trying to add a host to my /etc/hosts file so it could identify my chef server's URL (which is on the container's host). Otherwise it fails ssl verify at the intermediate step. If NetworkMode needs to be set to 'host' mode, is there another way around this?

**Comment by jkeiser** [comment]
@priminus I see ... the `host` networking was added so that we could reach the docker instance even if it was on docker-toolbox, but we can relax that for when people have actual chef servers. Let's give it a shot.

**Comment by jkeiser** [comment]
@priminus though, things *should* work just fine with chef-zero at this point, if local mode is your thing. I'm not sure if you are purposely running a real chef server or not.

**Comment by jkeiser** [comment]
@priminus it should turn off the `host` thing if you are not using local mode now ... give the latest commit  branch a spin?

**Comment by Priminus** [comment]
@jkeiser I'm testing this out locally with a chef-server on the same network so that when it's run with a real chef-server elsewhere, I know it works :) So yes, purposely for now.
I'll try the latest commit.

**Comment by Priminus** [comment]
@jkeiser getting this because 'connection' is null when 'docker_toolkit_transport' is being called
```ruby
[2016-03-15T18:40:22+00:00] DEBUG: NoMethodError: machine[app0.vagrant.local] (@recipe_files::/vagrant/deploy_single.rb line 29) had an error: NoMethodError: undefined method `connection' for nil:NilClass
/root/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-docker-0.8.0/lib/chef/provisioning/docker_driver/docker_transport.rb:174:in `docker_toolkit_transport'
/root/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-docker-0.8.0/lib/chef/provisioning/docker_driver/docker_container_machine.rb:110:in `build_converge_container'
/root/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-docker-0.8.0/lib/chef/provisioning/docker_driver/docker_container_machine.rb:22:in `setup_convergence'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:58:in `block in <class:Machine>'
```

**Comment by jkeiser** [comment]
grr. Fixed. Sorry for all the trouble, and I really appreciate you working with me so we can get this up and running :)

**Comment by jkeiser** [comment]
(Meantime, I'm trying an external chef server myself.)

**Comment by jkeiser** [comment]
Looks like for that one, I still need to remove at least some of the network stuff (ports in particular, so it doesn't try to bind multiple times). Fixing.

**Comment by jkeiser** [comment]
@priminus you can join me on https://gitter.im/chef/chef-provisioning if you want to be able to back and forth more :)

**Comment by jkeiser** [comment]
@priminus tested and updated ... I can do it using an external URL with ports.

**Comment by Priminus** [comment]
@jkeiser Left you a few messages on gitter :)
Still no hosts added with this
:add_hosts => "chefserver.vagrant.local=172.17.0.1"

[2016-03-16T17:35:38+00:00] DEBUG: Creating converge container with config {"Image"=>"sha256:07c86167cdc4264926fa5d2894e34a339ad27f730e8cc81a16cd21b7479e8eac", "HostConfig"=>{"PortBindings"=>{"443/tcp"=>[{"HostIp"=>"", "HostPort"=>""}]}}, "name"=>"chef-converge.app0.vagrant.local", "Cmd"=>["/bin/sh", "-c", "while true;do sleep 1000; done"]} ...

As a result I get this error:
```ruby
[2016-03-16T17:36:29+00:00] DEBUG: Re-raising exception: SocketError - Error connecting to https://chefserver.vagrant.local/organizations/chefserver/nodes/app0.vagrant.local - getaddrinfo: Name or service not known
                         /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
                           /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
```

**Comment by Priminus** [comment]
All works now!
